version: "2"
services:
  app:
    container_name: cyberpunk
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./cyberpunk:/cyberpunk/clones
    ports:
      - "27017:27017"