// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/28ef3d201b4271f3bb6c417b01a98d5706dd62a5/pouchdb-browser/index.d.ts
declare module 'pouchdb-browser' {
    const PouchDb: PouchDB.Static;
    export = PouchDb;
}
